# Generated by Django 5.1.1 on 2024-09-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer", models.CharField(max_length=100)),
                ("seller", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("proof_of_payment", models.ImageField(upload_to="proof_of_payments/")),
                ("lawyer_details", models.TextField()),
                ("seller_details", models.TextField()),
                ("is_verified", models.BooleanField(default=False)),
                ("smart_contract_address", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
